In [3]:
from __future__ import print_function
from keras.models import Sequential
from keras import layers
import numpy as np
from six.moves import range

In [359]:
class CharacterTable(object):
    def __init__(self,chars):
        print ('initializing these chars',chars)
        self.chars = sorted(set(chars))
        self.char_indices = dict((c, i) for i, c in enumerate(self.chars))
        print('char_indices',self.char_indices)
        self.indices_char = dict((i,c) for i,c in enumerate(self.chars))
        print('indices_char',self.indices_char)
        print('INITIALIZATION COMPLETE')
        print('#'*50)
        
    def encode(self,C,num_rows):
        print('ENCODING.....',C)
        print('num_rows->',num_rows)
        print('initializing a zeros numpy Array')
        print('Of shape->',num_rows, len(self.chars))
        x = np.zeros((num_rows, len(self.chars)))
        print('the np array',x)
        print('*'*20)
        print('begin one-hot encoding...')
        print('looping')
        for i,c in enumerate(C):
            print('i = ',i)
            print('c = ',c)
            print(x[i, self.char_indices[c]],'=',1)
            x[i, self.char_indices[c]] = 1
        
        print('Encoded',C, 'to',x)
        
        return x
    
    def decode(self,x,calc_argmax=True):
        if calc_argmax:
            x = x.argmax(axis=-1)
        return ''.join(self.indices_char[x] for x in x)

In [360]:
chars = '0123456789+ '
ctable = CharacterTable(chars)

initializing these chars 0123456789+ 
char_indices {' ': 0, '+': 1, '0': 2, '1': 3, '2': 4, '3': 5, '4': 6, '5': 7, '6': 8, '7': 9, '8': 10, '9': 11}
indices_char {0: ' ', 1: '+', 2: '0', 3: '1', 4: '2', 5: '3', 6: '4', 7: '5', 8: '6', 9: '7', 10: '8', 11: '9'}
INITIALIZATION COMPLETE
##################################################


In [338]:
DIGITS = 3
f = lambda: int(''.join(np.random.choice(list('0123456789'))
                    for i in range(np.random.randint(1, DIGITS + 1))))
a, b = f(), f()
print('befor sorting......')
q = '{}+{}'.format(a, b)
print(q)
key = tuple(sorted((a, b)))
print('After sorting.....')
q = '{}+{}'.format(a, b)
print(q)
ans = str(a+b)
print('ans = ',ans)

befor sorting......
739+0
After sorting.....
739+0
ans =  739


In [339]:
MAXLEN = DIGITS + 1 + DIGITS
# apply padding to meet max len of question
query = q + ' ' * (MAXLEN - len(q))
print('`',query.replace(' ','*'),'`')
print(len(query))

` 739+0** `
7


In [340]:
np.random.randint(1,4)

2

In [341]:
[np.random.choice(list('0123456789')) for i in range(np.random.randint(1,4))]

['6', '4']

In [342]:
query = query[::-1]
ans = ans

In [343]:
x = np.zeros((1,7,len(chars)),dtype=np.int)
len(x)

1

In [344]:
x.shape

(1, 7, 12)

In [345]:
gd = []
for i, sentence in enumerate([query]):
    print('#'*100)
    print('i = ',i)
    print('CHANGING',x[i])
#     x[i] = ctable.encode(sentence,MAXLEN)
    print('XXX',ctable.encode(sentence,MAXLEN))
#     x[i] = ctable.encode(sentence,MAXLEN)
    gd = ctable.encode(sentence,MAXLEN)
    print('RETURNS',x[i])

print('#'*50)
print(x[0][0])
print('GDDDD',gd)
x[0] = gd
print('X[O]',x[0])

####################################################################################################
i =  0
CHANGING [[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]
ENCODING.....   0+937
num_rows-> 7
initializing a zeros numpy Array
Of shape-> 7 12
the np array [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
********************
begin one-hot encoding...
looping
i =  0
c =   
0.0 = 1
i =  1
c =   
0.0 = 1
i =  2
c =  0
0.0 = 1
i =  3
c =  +
0.0 = 1
i =  4
c =  9
0.0 = 1
i =  5
c =  3
0.0 = 1
i =  6
c =  7
0.0 = 1
Encoded   0+937 to [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.

In [346]:
ans


'739'

In [347]:
y = np.zeros((1,DIGITS+1,len(chars)),dtype=int)
y.shape

(1, 4, 12)

In [348]:
for i,sentence in enumerate([ans]):
    y[i] = ctable.encode(sentence, DIGITS+1)
    
print('Encoded ans to',y[i])

ENCODING..... 739
num_rows-> 4
initializing a zeros numpy Array
Of shape-> 4 12
the np array [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
********************
begin one-hot encoding...
looping
i =  0
c =  7
0.0 = 1
i =  1
c =  3
0.0 = 1
i =  2
c =  9
0.0 = 1
Encoded 739 to [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Encoded ans to [[0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0]]


In [349]:
for i,s in enumerate([ans]):
    print(i,' ',s)

0   739


In [350]:
#shuffle
gg = [
    [[1]],
    [[3]],
    [[6]],
    [[9]]
]
indices = np.arange(len(gg))
indices

array([0, 1, 2, 3])

In [351]:
np.random.shuffle([0,1,2])
indices

array([0, 1, 2, 3])

In [352]:
len(y)

1

In [353]:
gg[(0,1,4)]

TypeError: list indices must be integers or slices, not tuple

In [354]:
128/2

64.0

In [355]:
np.argmax([0,0,0,1,0,0])

3

In [381]:
aabb = np.array([0,1,0,0,1,0,0,0,0])
aabb.argmax()

1

In [380]:
ctable.decode(x[0][0],calc_argmax=True)

TypeError: 'numpy.int64' object is not iterable

In [365]:
ctable.decode(y[0])

'739 '

In [372]:
y[0].argmax(axis=-1)

array([ 9,  5, 11,  0])

In [377]:
y[0].argmax(axis=-1)

array([ 9,  5, 11,  0])