In [4]:
from sklearn import  datasets
import numpy as np
import matplotlib as plt
from sklearn.neighbors import  KNeighborsClassifier

In [5]:
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
y_uniques = np.unique(iris_y)
print(y_uniques)

[0 1 2]


In [6]:
# K-Nearest neighbors classifier
# split iris data in train and test data
# A random permutation, to split the data randomly
np.random.seed(0)
indices = np.random.permutation(len(iris_y))
print(indices)

[114  62  33 107   7 100  40  86  76  71 134  51  73  54  63  37  78  90
  45  16 121  66  24   8 126  22  44  97  93  26 137  84  27 127 132  59
  18  83  61  92 112   2 141  43  10  60 116 144 119 108  69 135  56  80
 123 133 106 146  50 147  85  30 101  94  64  89  91 125  48  13 111  95
  20  15  52   3 149  98   6  68 109  96  12 102 120 104 128  46  11 110
 124  41 148   1 113 139  42   4 129  17  38   5  53 143 105   0  34  28
  55  75  35  23  74  31 118  57 131  65  32 138  14 122  19  29 130  49
 136  99  82  79 115 145  72  77  25  81 140 142  39  58  88  70  87  36
  21   9 103  67 117  47]


In [8]:
len(np.unique(indices))

150

In [9]:
len(indices)

150

In [10]:
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test = iris_X[indices[-10:]]
iris_y_test = iris_y[indices[-10:]]

In [11]:
# create and fit a  nearest-neighbor classifier
knn = KNeighborsClassifier()
knn.fit(iris_X_train,iris_y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [12]:
knn.predict(iris_X_test)

array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])

In [13]:
iris_y_test

array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])