In [5]:
import pandas as pd
import numpy as np
import math

In [6]:
filePath = './titanic.xls'
df = pd.read_excel(filePath)
df
# pd.read_csv


pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

In [7]:
cols_to_remove = ['home.dest','boat','body','fare','cabin','embarked','parch','sibsp']
df = df.drop(cols_to_remove,axis=1)
df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  ticket  
0     female  29.0000   24160  
1       male   0.9167  113781  
2     female   2.0000  113781  
3       male  30.0000  113781  
4     female  25.0000  113781  
...      ...      ...     ...  
1304  female  14.5000    2665  
1305  female      NaN    2665  
1306    male  26.5000    2656  
1307    male  27.0000    2670  
1308    male  29.0000  315082  

[1309 rows x 6 columns]

In [8]:
# sort the names
names = [name.split(',')[0]for name in df['name']]
df['name'] = names
df

pclass  survived       name     sex      age  ticket
0          1         1      Allen  female  29.0000   24160
1          1         1    Allison    male   0.9167  113781
2          1         0    Allison  female   2.0000  113781
3          1         0    Allison    male  30.0000  113781
4          1         0    Allison  female  25.0000  113781
...      ...       ...        ...     ...      ...     ...
1304       3         0     Zabour  female  14.5000    2665
1305       3         0     Zabour  female      NaN    2665
1306       3         0   Zakarian    male  26.5000    2656
1307       3         0   Zakarian    male  27.0000    2670
1308       3         0  Zimmerman    male  29.0000  315082

[1309 rows x 6 columns]

In [9]:
df[0:50]

pclass  survived                    name     sex      age    ticket
0        1         1                   Allen  female  29.0000     24160
1        1         1                 Allison    male   0.9167    113781
2        1         0                 Allison  female   2.0000    113781
3        1         0                 Allison    male  30.0000    113781
4        1         0                 Allison  female  25.0000    113781
5        1         1                Anderson    male  48.0000     19952
6        1         1                 Andrews  female  63.0000     13502
7        1         0                 Andrews    male  39.0000    112050
8        1         1                Appleton  female  53.0000     11769
9        1         0            Artagaveytia    male  71.0000  PC 17609
10       1         0                   Astor    male  47.0000  PC 17757
11       1         1                   Astor  female  18.0000  PC 17757
12       1         1                  Aubart  female  24.0000  PC 17477
13       1         1                  Barber  female  26.0000     19877
14       1         1               Barkworth    male  80.0000     27042
15       1         0                 Baumann    male      NaN  PC 17318
16       1         0                  Baxter    male  24.0000  PC 17558
17       1         1                  Baxter  female  50.0000  PC 17558
18       1         1                 Bazzani  female  32.0000     11813
19       1         0                 Beattie    male  36.0000     13050
20       1         1                Beckwith    male  37.0000     11751
21       1         1                Beckwith  female  47.0000     11751
22       1         1                    Behr    male  26.0000    111369
23       1         1                  Bidois  female  42.0000  PC 17757
24       1         1                    Bird  female  29.0000  PC 17483
25       1         0                Birnbaum    male  25.0000     13905
26       1         1                  Bishop    male  25.0000     11967
27       1         1                  Bishop  female  19.0000     11967
28       1         1                Bissette  female  35.0000  PC 17760
29       1         1  Bjornstrom-Steffansson    male  28.0000    110564
30       1         0               Blackwell    male  45.0000    113784
31       1         1                   Blank    male  40.0000    112277
32       1         1                 Bonnell  female  30.0000     36928
33       1         1                 Bonnell  female  58.0000    113783
34       1         0                Borebank    male  42.0000    110489
35       1         1                   Bowen  female  45.0000  PC 17608
36       1         1                Bowerman  female  22.0000    113505
37       1         1                 Bradley    male      NaN    111427
38       1         0                   Brady    male  41.0000    113054
39       1         0                Brandeis    male  48.0000  PC 17591
40       1         0                   Brewe    male      NaN    112379
41       1         1                   Brown  female  44.0000  PC 17610
42       1         1                   Brown  female  59.0000     11769
43       1         1                Bucknell  female  60.0000     11813
44       1         1                   Burns  female  41.0000     16966
45       1         0                    Butt    male  45.0000    113050
46       1         0                  Cairns    male      NaN    113798
47       1         1              Calderhead    male  42.0000  PC 17476
48       1         1                  Candee  female  53.0000  PC 17606
49       1         1                 Cardeza    male  36.0000  PC 17755

In [10]:
df['age'] = df['age'].fillna(0)
print(df)
age = [int(str(math.ceil(ag)).split('.')[0]) if type(ag)== float else 0 for ag in df['age']]
df['age'] = age
print(df)

      pclass  survived       name     sex      age  ticket
0          1         1      Allen  female  29.0000   24160
1          1         1    Allison    male   0.9167  113781
2          1         0    Allison  female   2.0000  113781
3          1         0    Allison    male  30.0000  113781
4          1         0    Allison  female  25.0000  113781
...      ...       ...        ...     ...      ...     ...
1304       3         0     Zabour  female  14.5000    2665
1305       3         0     Zabour  female   0.0000    2665
1306       3         0   Zakarian    male  26.5000    2656
1307       3         0   Zakarian    male  27.0000    2670
1308       3         0  Zimmerman    male  29.0000  315082

[1309 rows x 6 columns]
      pclass  survived       name     sex  age  ticket
0          1         1      Allen  female   29   24160
1          1         1    Allison    male    1  113781
2          1         0    Allison  female    2  113781
3          1         0    Allison    male   30 

In [11]:
[tck for tck in df['ticket']]

[24160,
 113781,
 113781,
 113781,
 113781,
 19952,
 13502,
 112050,
 11769,
 'PC 17609',
 'PC 17757',
 'PC 17757',
 'PC 17477',
 19877,
 27042,
 'PC 17318',
 'PC 17558',
 'PC 17558',
 11813,
 13050,
 11751,
 11751,
 111369,
 'PC 17757',
 'PC 17483',
 13905,
 11967,
 11967,
 'PC 17760',
 110564,
 113784,
 112277,
 36928,
 113783,
 110489,
 'PC 17608',
 113505,
 111427,
 113054,
 'PC 17591',
 112379,
 'PC 17610',
 11769,
 11813,
 16966,
 113050,
 113798,
 'PC 17476',
 'PC 17606',
 'PC 17755',
 'PC 17755',
 695,
 113059,
 113059,
 113760,
 113760,
 113760,
 113760,
 19924,
 17770,
 19877,
 19877,
 'W.E.P. 5734',
 'W.E.P. 5734',
 113806,
 113806,
 'PC 17608',
 110152,
 'PC 17594',
 113505,
 112051,
 13508,
 13508,
 113781,
 110465,
 5727,
 'PC 17756',
 'PC 17756',
 'PC 17756',
 11770,
 113791,
 'WE/P 5735',
 'WE/P 5735',
 112901,
 'PC 17599',
 'PC 17599',
 113055,
 113804,
 113781,
 'F.C. 12750',
 'F.C. 12750',
 17474,
 17474,
 33638,
 33638,
 33638,
 'PC 17761',
 'PC 17558',
 'PC 17761',

In [12]:
# vectorize
class Vect_tickets:
    def __init__(self,dframecolumn):
        self.indices_ticket = dict()
        self.ticket_indices = dict()
        counter = 0;
        for tkt in dframecolumn:
            if counter == 0:
                print('tkt',tkt)
            if tkt not in self.ticket_indices:
                counter = counter + 1
                self.ticket_indices[tkt] = counter;
        
        for k in self.ticket_indices:
            valuee = self.ticket_indices[k]
            self.indices_ticket[valuee] = k
        
#         print('indices_ticket',self.indices_ticket)
#         print('self.ticket_indices',self.ticket_indices)
    
    def encode(self,dframecol):
        correctedDfCol = []
        for c in iter(dframecol):
            correctedDfCol.append(self.ticket_indices[c])
        
        return np.array(correctedDfCol)
    
    def decode(self,dframecoltoDecode):
        correctedDfCol2 = []
        for c in iter(dframecol):
            correctedDfCol2.append(self.indices_ticket[c])
        
        return correctedDfCol2
            
    
        
        
        
        
        
        

In [13]:
not_encoded_tickets_DF = df['ticket']

vect_tickets = Vect_tickets(not_encoded_tickets_DF)
encoded_tickets = vect_tickets.encode(not_encoded_tickets_DF)
print(len(not_encoded_tickets_DF),len(encoded_tickets))
df['ticket'] = encoded_tickets
df

tkt 24160
1309 1309


pclass  survived       name     sex  age  ticket
0          1         1      Allen  female   29       1
1          1         1    Allison    male    1       2
2          1         0    Allison  female    2       2
3          1         0    Allison    male   30       2
4          1         0    Allison  female   25       2
...      ...       ...        ...     ...  ...     ...
1304       3         0     Zabour  female   15     936
1305       3         0     Zabour  female    0     936
1306       3         0   Zakarian    male   27     937
1307       3         0   Zakarian    male   27     938
1308       3         0  Zimmerman    male   29     939

[1309 rows x 6 columns]

In [14]:
df['sex'].replace('female',0,inplace=True)
df['sex'].replace('male',1,inplace=True)
df

pclass  survived       name  sex  age  ticket
0          1         1      Allen    0   29       1
1          1         1    Allison    1    1       2
2          1         0    Allison    0    2       2
3          1         0    Allison    1   30       2
4          1         0    Allison    0   25       2
...      ...       ...        ...  ...  ...     ...
1304       3         0     Zabour    0   15     936
1305       3         0     Zabour    0    0     936
1306       3         0   Zakarian    1   27     937
1307       3         0   Zakarian    1   27     938
1308       3         0  Zimmerman    1   29     939

[1309 rows x 6 columns]

In [15]:
df.drop(['name'],inplace=True,axis=1)
df

pclass  survived  sex  age  ticket
0          1         1    0   29       1
1          1         1    1    1       2
2          1         0    0    2       2
3          1         0    1   30       2
4          1         0    0   25       2
...      ...       ...  ...  ...     ...
1304       3         0    0   15     936
1305       3         0    0    0     936
1306       3         0    1   27     937
1307       3         0    1   27     938
1308       3         0    1   29     939

[1309 rows x 5 columns]

In [16]:
# print(df.to_xarray[0:])
df = df[['pclass','survived','sex','age',]]
dfLabel = df['survived']
dfTrain = df.drop(['survived'],axis=1)
# dfArr = np.array(a)
dfTrain = np.array(dfTrain)
dfLabel = np.array(dfLabel)
dfLabel
dfTrain

array([[ 1,  0, 29],
       [ 1,  1,  1],
       [ 1,  0,  2],
       ...,
       [ 3,  1, 27],
       [ 3,  1, 27],
       [ 3,  1, 29]])

In [17]:
# slit data
testLen = 20
X_train = dfTrain[:-testLen]
X_test = dfTrain[-testLen:]

y_train = dfLabel[:-testLen]
y_test = dfLabel[-testLen:]

# y_test

In [18]:
# make model
print(X_train.shape)
X_train00 = np.expand_dims(X_train,axis=1)

print(X_train00.shape)

(1289, 3)
(1289, 1, 3)


In [19]:
y_test.shape

(20,)

In [20]:
y_train.shape

(1289,)

In [21]:
print(X_train.shape)
print(X_train)

(1289, 3)
[[ 1  0 29]
 [ 1  1  1]
 [ 1  0  2]
 ...
 [ 3  0 38]
 [ 3  1 51]
 [ 3  1 18]]


In [22]:
print(X_test.shape)
print(X_test)

(20, 3)
[[ 3  1 21]
 [ 3  0 47]
 [ 3  1  0]
 [ 3  1  0]
 [ 3  1  0]
 [ 3  1 29]
 [ 3  1 21]
 [ 3  1 27]
 [ 3  1  0]
 [ 3  1 36]
 [ 3  1 27]
 [ 3  0 15]
 [ 3  1 46]
 [ 3  1  0]
 [ 3  1  0]
 [ 3  0 15]
 [ 3  0  0]
 [ 3  1 27]
 [ 3  1 27]
 [ 3  1 29]]


In [23]:
X_test00 = np.expand_dims(X_test,axis=1)
print(X_test00.shape)
print(X_test00)

(20, 1, 3)
[[[ 3  1 21]]

 [[ 3  0 47]]

 [[ 3  1  0]]

 [[ 3  1  0]]

 [[ 3  1  0]]

 [[ 3  1 29]]

 [[ 3  1 21]]

 [[ 3  1 27]]

 [[ 3  1  0]]

 [[ 3  1 36]]

 [[ 3  1 27]]

 [[ 3  0 15]]

 [[ 3  1 46]]

 [[ 3  1  0]]

 [[ 3  1  0]]

 [[ 3  0 15]]

 [[ 3  0  0]]

 [[ 3  1 27]]

 [[ 3  1 27]]

 [[ 3  1 29]]]


In [24]:
# 1 keras
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Input
from keras.losses import mean_squared_error,sparse_categorical_crossentropy

model = Sequential()
model.add(Dense(3,input_shape=(1,3), activation='relu'))
model.add(Flatten())
# model.add(Dense(4, activation='softmax'))
model.add(Dense(4, activation='relu'))
model.add(Dense(2, activation='sigmoid'))
model.add(Dropout(0.25))
model.add(Dense(1,activation='sigmoid'))


model.compile('sgd',loss='mean_squared_error',metrics=['accuracy'])
model.summary()

# for one in X_train:
#     print()
#     model.fit(np.expand_dims([one],axis=1),y_train, epochs=1)

model.fit(X_train00,y_train, epochs=40, batch_size=20)
# print(X_train[0][0])
pred = model.predict(X_train00)

Using TensorFlow backend.
/home/george/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/george/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/george/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/george/anaconda3/lib/python3.7/site-packages/tenso

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1, 3)              12        
_________________________________________________________________
flatten_1 (Flatten)          (None, 3)                 0         
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 16        
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 10        
_________________________________________________________________
dropout_1 (Dropout)          (None, 2)                 0         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 3         
Total params: 41
Trainable params: 41
Non-trainable params: 0
__________________________________________________________

In [25]:
pred = pred
pred
# [1, 1, 0, 0, 0, 1, 1, 0, 1, 0]

array([[0.38504016],
       [0.38504016],
       [0.38504016],
       ...,
       [0.38504016],
       [0.38504016],
       [0.38504016]], dtype=float32)

In [26]:
arr2 = []
for num in pred:
    if float(num[0])>0.5:
        arr2.append(1)
    else:
        arr2.append(0)

In [27]:
arr2

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [28]:
# y_test
y_train[:10]

array([1, 1, 0, 0, 0, 1, 1, 0, 1, 0])

In [29]:
from sklearn.metrics import confusion_matrix
confusion_matrix(arr2,y_train)
c = 0;
if 1 in arr2:
    c+=1
    print(c)

In [ ]:
# SKLEARN

In [ ]:
from sklearn import svm
clf = svm.SVC(kernel='poly')
clf = clf.fit(X_train,y_train)

/home/george/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [ ]:
clf.predict(X_test)

In [1]:
y_test

NameError: name 'y_test' is not defined