In [40]:
import pandas as pd
import math
import numpy as np
from sklearn import preprocessing, svm
from sklearn.model_selection import cross_validate
from sklearn.linear_model import LinearRegression

In [19]:
df = pd.read_csv('quandleDF.csv')
df.head()

Date    Open    High     Low    Close      Volume  Ex-Dividend  \
0  2004-08-19  100.01  104.06   95.96  100.335  44659000.0          0.0   
1  2004-08-20  101.01  109.08  100.50  108.310  22834300.0          0.0   
2  2004-08-23  110.76  113.48  109.05  109.400  18256100.0          0.0   
3  2004-08-24  111.24  111.60  103.57  104.870  15247300.0          0.0   
4  2004-08-25  104.76  108.00  103.88  106.000   9188600.0          0.0   

   Split Ratio  Adj. Open  Adj. High   Adj. Low  Adj. Close  Adj. Volume  
0          1.0  50.159839  52.191109  48.128568   50.322842   44659000.0  
1          1.0  50.661387  54.708881  50.405597   54.322689   22834300.0  
2          1.0  55.551482  56.915693  54.693835   54.869377   18256100.0  
3          1.0  55.792225  55.972783  51.945350   52.597363   15247300.0  
4          1.0  52.542193  54.167209  52.100830   53.164113    9188600.0

In [20]:
df = df[['Adj. Open','Adj. High','Adj. Low','Adj. Close','Adj. Volume']]
df.head()

Adj. Open  Adj. High   Adj. Low  Adj. Close  Adj. Volume
0  50.159839  52.191109  48.128568   50.322842   44659000.0
1  50.661387  54.708881  50.405597   54.322689   22834300.0
2  55.551482  56.915693  54.693835   54.869377   18256100.0
3  55.792225  55.972783  51.945350   52.597363   15247300.0
4  52.542193  54.167209  52.100830   53.164113    9188600.0

In [21]:
df['HL_PCT'] = (df['Adj. High'] - df['Adj. Close']) / df['Adj. Close']*100.0
df['PCT_change'] = (df['Adj. Close'] - df['Adj. Open']) / df['Adj. Open']*100.0

In [22]:
df = df[['Adj. Close','HL_PCT','PCT_change','Adj. Volume']]
df.head()

Adj. Close    HL_PCT  PCT_change  Adj. Volume
0   50.322842  3.712563    0.324968   44659000.0
1   54.322689  0.710922    7.227007   22834300.0
2   54.869377  3.729433   -1.227880   18256100.0
3   52.597363  6.417469   -5.726357   15247300.0
4   53.164113  1.886792    1.183658    9188600.0

In [23]:
forecast_col = 'Adj. Close'

In [24]:
df.fillna(-99999, inplace=True)

In [31]:
forecast_out = int(math.ceil(0.01*len(df)))
df['label'] = df[forecast_col].shift(-forecast_out)
df.dropna(inplace=True)
df.head()

Adj. Close    HL_PCT  PCT_change  Adj. Volume      label
0   50.322842  3.712563    0.324968   44659000.0  59.373280
1   54.322689  0.710922    7.227007   22834300.0  60.597057
2   54.869377  3.729433   -1.227880   18256100.0  60.100525
3   52.597363  6.417469   -5.726357   15247300.0  59.313094
4   53.164113  1.886792    1.183658    9188600.0  63.626409

In [36]:
X = np.array(df.drop(['label'],1))
y = np.array(df['label'])
print('x b4 preprocessing',X)
X = preprocessing.scale(X)
print('x after preprocessing',X)


x b4 preprocessing [[ 5.03228418e+01  3.71256291e+00  3.24967503e-01  4.46590000e+07]
 [ 5.43226889e+01  7.10922353e-01  7.22700723e+00  2.28343000e+07]
 [ 5.48693765e+01  3.72943327e+00 -1.22788010e+00  1.82561000e+07]
 ...
 [ 4.37340027e+02  1.60783504e+00 -1.52237255e+00  4.40510000e+06]
 [ 4.39857799e+02  3.03306727e-01  9.22921126e-01  4.13560000e+06]
 [ 4.38874764e+02  1.10394953e+00 -5.74934667e-01  4.48550000e+06]]
x after preprocessing [[-2.46051607  1.99554242  0.20367611  3.82919642]
 [-2.4098142  -0.39885425  4.28693283  1.3598953 ]
 [-2.40288442  2.00899984 -0.71499079  0.8419063 ]
 ...
 [ 2.44529524  0.31660941 -0.88921295 -0.72523047]
 [ 2.4772104  -0.72400761  0.55742634 -0.75572237]
 [ 2.4647495  -0.08533804 -0.32870732 -0.71613381]]


In [38]:
# X = X[:-forecast_out+1]
df.dropna(inplace=True)
y = np.array(df['label'])
print(len(X),len(y))

2199 2221
