In [2]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
tf.enable_eager_execution()

In [3]:
# Layers: common sets of useful operations
##############################################

In [4]:
# In the (tf.keras) layers package, layers are objects.
# To construct a layer, simply construct the object.
# Most layers take as a first argument the number of 
# outputs dimensions / channels.
layer = tf.keras.layers.Dense(100)
# The number of input dimensions is often unnecessary, as it
# can be inferred the first time the layer is used, but it can 
# be provided if you want to specify it manually, which is 
# useful in some complex models.
layers = tf.keras.layers.Dense(10, input_shape=(None,5))


In [5]:
# To use a layer, simply call it.
layer(tf.zeros([10,5]))

<tf.Tensor: id=29, shape=(10, 100), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 

In [7]:
# Layers have many useful methos. For example, you can inspect
# all variables in a layer using `layer.variables` and 
# trainable variables using `layer.trainable_variables`.
# In this case a fully-connected layer will have variables
# for weights and biases
layer.variables

[<tf.Variable 'dense/kernel:0' shape=(5, 100) dtype=float32, numpy=
 array([[-0.09680159,  0.13405772, -0.23887354,  0.0005852 , -0.17341083,
          0.2388549 , -0.14115886,  0.03481625,  0.11024748, -0.12936339,
          0.20863976,  0.05590476, -0.21312864, -0.18221481, -0.19740605,
         -0.20674491, -0.23889595,  0.01485698,  0.19680871,  0.12438978,
         -0.02485622, -0.03637654, -0.10542737, -0.11718638, -0.14606482,
          0.19222237,  0.05290551,  0.1994885 , -0.15359569, -0.12860936,
         -0.04444189, -0.00857937,  0.20345198,  0.21678604,  0.13439785,
         -0.16697177,  0.0136167 , -0.11108653, -0.09517235,  0.00290789,
         -0.08293977,  0.05326702, -0.08537446,  0.18072285,  0.0544825 ,
          0.0494227 ,  0.07514314, -0.1151906 , -0.04932432,  0.10270612,
         -0.18567047,  0.01916189,  0.04062064,  0.23193477,  0.19225092,
          0.11623819,  0.20063446, -0.2228774 ,  0.00431949, -0.10611476,
         -0.22147223, -0.09024109,  0.093099

In [9]:
# The variables are also accessible through nice accessors
layer.kernel, layer.bias

(<tf.Variable 'dense/kernel:0' shape=(5, 100) dtype=float32, numpy=
 array([[-0.09680159,  0.13405772, -0.23887354,  0.0005852 , -0.17341083,
          0.2388549 , -0.14115886,  0.03481625,  0.11024748, -0.12936339,
          0.20863976,  0.05590476, -0.21312864, -0.18221481, -0.19740605,
         -0.20674491, -0.23889595,  0.01485698,  0.19680871,  0.12438978,
         -0.02485622, -0.03637654, -0.10542737, -0.11718638, -0.14606482,
          0.19222237,  0.05290551,  0.1994885 , -0.15359569, -0.12860936,
         -0.04444189, -0.00857937,  0.20345198,  0.21678604,  0.13439785,
         -0.16697177,  0.0136167 , -0.11108653, -0.09517235,  0.00290789,
         -0.08293977,  0.05326702, -0.08537446,  0.18072285,  0.0544825 ,
          0.0494227 ,  0.07514314, -0.1151906 , -0.04932432,  0.10270612,
         -0.18567047,  0.01916189,  0.04062064,  0.23193477,  0.19225092,
          0.11623819,  0.20063446, -0.2228774 ,  0.00431949, -0.10611476,
         -0.22147223, -0.09024109,  0.093099

In [12]:
# Implementing custom layers
##############################
# The best way is 
## Extend the tf.keras.Layer class
##and implementing: *(__init__), where you can do all input-independent
# initialization*
# *(build), where you know the shapes of the input tensors 
# and can do the rest of the initialization*
# *(call), where you do the forward computation*

class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self,num_outputs):
        super(MyDenseLayer,self).__init__()
        self.num_outputs = num_outputs
    
    def build(self,input_shape):
        self.kernel = self.add_variable('kernel',
                                       shape=[int(input_shape[-1]),
                                             self.num_outputs])
        
    def call(self,input):
        return tf.matmul(input, self.kernel)
    
layer = MyDenseLayer(10)

_ = layer(tf.zeros([10,5])) # Calling the layer `.builds it`.
_

<tf.Tensor: id=76, shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [13]:
print([var.name for var in layer.trainable_variables])

['my_dense_layer_2/kernel:0']


In [14]:
# Models: Composing Layers
#############################
# Many interesting layer-like things in machine learning
# models are implemented by composing existing layers.
# Typically you can inherit from (keras.Model) when you need 
# the model methods like:
## (Model.fit), (Model.evaluate) and (Model.save) etc
#######
# One othe feature provided by (keras.Model) instead of 
# (keras.layers.Layer) is that in addition to tracking 
# variables, a (keras.Model) also tracks its internal layers,
# making them easier to inspect.
###################
'eg. Here is a ResNet block'
class ResnetIdentityBlock(tf.keras.Model):
    def __init__(self,kernel_size, filters):
        super(ResnetIdentityBlock,self).__init__(name='')
        filters1,filters2,filters3 = filters
        
        self.conv2a = tf.keras.layers.Conv2D(filters1, (1,1))
        self.bn2a = tf.keras.layers.BatchNormalization()
        
        self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size,padding='same')
        self.bn2b = tf.keras.layers.BatchNormalization()
        
        self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
        self.bn2c = tf.keras.layers.BatchNormalization()
        
    def call(self, input_tensor, training=False):
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training=training)
        x = tf.nn.relu(x)
        
        x = self.conv2b(x)
        x = self.bn2b(x, training=training)
        x = tf.nn.relu(x)
    
    
        x = self.conv2c(x)
        x = self.bn2c(x, training=training)

        x += input_tensor
        return tf.nn.relu(x)
    
block = ResnetIdentityBlock(1, [1,2,3])



In [16]:
block.layers

In [17]:
len(block.variables)

0

In [18]:
block.summary()

ValueError: This model has not yet been built. Build the model first by calling `build()` or calling `fit()` with some data, or specify an `input_shape` argument in the first layer(s) for automatic build.

In [19]:
# (tf.keras.Sequential)
my_seq = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1, 1),
                                                    input_shape=(
                                                        None, None, 3)),
                             tf.keras.layers.BatchNormalization(),
                             tf.keras.layers.Conv2D(2, 1,
                                                    padding='same'),
                             tf.keras.layers.BatchNormalization(),
                             tf.keras.layers.Conv2D(3, (1, 1)),
                             tf.keras.layers.BatchNormalization()])
my_seq(tf.zeros([1, 2, 3, 3]))


<tf.Tensor: id=499, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [20]:
my_seq.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, None, None, 1)     4         
_________________________________________________________________
batch_normalization_3 (Batch (None, None, None, 1)     4         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, None, None, 2)     4         
_________________________________________________________________
batch_normalization_4 (Batch (None, None, None, 2)     8         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, None, None, 3)     9         
_________________________________________________________________
batch_normalization_5 (Batch (None, None, None, 3)     12        
Total params: 41
Trainable params: 29
Non-trainable params: 12
___________________________________________________________